### PR TITLE
2019 12 minutes

### PR DESCRIPTION
**Pull request by ChristinaLK**
@tkphd @aturner-epcc @psteinb can you do a quick check?

### CODE REVIEW

**Comment by tkphd** [comment]
Proposed changes in #6.

**Comment by ChristinaLK** [comment]
:+1: willing to close this in favor of #6

**Comment by tkphd** [comment]
Wait -- #6 is a request to merge into your branch. Plz don't close this PR.

**Comment by ChristinaLK** [comment]
LGTM.

**Pull request merged**
